### ISSUE TITLE
please publish on curse.com

### ISSUE THREAD

**Issue by fommil** [e-dog/ProceduralFairings#12]
I am very happy that you're using github and I wish all KSP adon devs were doing so, but it looks like there is a trend to publish all the binaries on curse. I must admit, this makes it really easy to stay up-to-date with all preferred mods because they allow "favourite" adons to be marked and downloaded in bulk (very useful when a new version of kerbal is released!)

**Comment by kupiakos** [comment]
I'd recommend a look at CKAN. It seems to work pretty well.

**Comment by fommil** [comment]
I've been using ckan for a few weeks, sorry should have closed this ticket
