### ISSUE TITLE
Cargo stays shielded after fairings destroyed (possibly FAR/DRE related)

### ISSUE THREAD

**Issue by MrNukealizer** [e-dog/ProceduralFairings#14]
I suspect the problem is that when a fairing is destroyed it doesn't update the game that the cargo is unprotected like it does when jettisoned. 

I was doing a reentry test with FAR and Deadly Reentry installed when the following happened. The craft was a basic rocket with everything except the engine inside a fairing and the engine on the bottom of the ring.

The craft came in fast enough that half of the fairing burned up, causing a sudden flip that ripped the engine off due to aerodynamic stress. A few seconds later the other half of the fairing burned up. By that time the cargo should have already been damaged by heat or aerodynamics but was still intact. Even after both halves of the fairing had burned up the cargo and ring were not heating up at all. Even going straight backwards the ring was unaffected. At that point I noticed I wasn't losing any speed and FAR was said the terminal velocity was infinite. To be sure I did another orbit passing below 23k meters and my orbit was unchanged, so the craft obviously no longer had any drag.

I tested the same craft again as well as three other designs and every time the parts inside the fairing as well as the ring were dragless and immune to heat after the rest of the crafts were destroyed. I didn't think to test inline fairings though.

**Comment by e-dog** [comment]
You should report it to DRE since it destroys the overheated parts in the first place. Tell them to contact me if they need me to change something in the PF code to fix that.

**Comment by MrNukealizer** [comment]
Ok, will do. After looking through some of the code for this and a couple other mods, I now see where I was thinking about things wrong.

**Comment by MrNukealizer** [comment]
I just tested more and it happens with stock and B9 cargo bays too so definitely not a problem with this mod.
