### ISSUE TITLE
Module documentation

### ISSUE THREAD

**Issue by futrtrubl** [e-dog/ProceduralFairings#16]
Is there any documentation for the fields in the modules?
I want to fiddle with fairing shapes but I have no idea what the numbers mean for baseConeShape and noseConeShape in ProceduralFairingSide.

**Comment by e-dog** [comment]
Quoting from the old forum post:

As for fairing shape: Bezier spline is used. It has two endpoints (on the spline) and two control points (off the spline). The endpoints are fixed at (0, 0) and (1, 1) to make a cone, which is then scaled as needed to match required diameter and height. The two control points between them are specified in the config file, as you see. The four numbers are their coordinates: x1, y1, x2, y2. That's all relative to the (0, 0) ... (1, 1) range so it can be scaled/stretched later.

It's easier to tune it in some program (2D or 3D) that has Bezier splines to match the shape you want to create and then measure the control point coordinates and scale them to the 0...1 range.

**Comment by futrtrubl** [comment]
Thanks muchly!
