### ISSUE TITLE
drag cubes and part extents not properly updated

### ISSUE THREAD

**Issue by assassinacc** [e-dog/ProceduralFairings#21]
If used as aeroshell behind a heatshield the fairings get full heating and will burn up. see: http://imgur.com/a/04yCy

**Comment by e-dog** [comment]
Are you sure it's part extents / drag cubes and not a heat transfer issue?

**Comment by assassinacc** [comment]
yeah, definetly. you can see the position of the overheating gizmos are way below the heatshield. and on the termal view you see all parts above the heatshield are fine, just the fairings get full heating like the heatshield itself.

**Comment by NathanKell** [comment]
I encounter this as well.

**Comment by NathanKell** [comment]
Example:
[![](http://i.imgur.com/Rris6fIl.png)](http://i.imgur.com/Rris6fI.png)

**Comment by NathanKell** [comment]
Note: Moved slightly off retrograde, but this happens even when 100% exactly on retrograde. The fairings are behind the heat shield and should be 100% occluded (and would be if they were regular parts of that shape).
And note where the gauges are drawn!

**Comment by assassinacc** [comment]
I can entirely confirm that.

**Comment by NathanKell** [comment]
@e-dog this appears to be because...you don't actually render any cubes if FAR is installed. That breaks thermodynamics, period. :(
