### ISSUE TITLE
Procedural fairings offsetting 

### ISSUE THREAD

**Issue by rsparkyc** [e-dog/ProceduralFairings#26]
There was a bug mentioned in the forums that seemed to be fixed by a build 3.20b2, however I can't seem to find that build (or the code for it) anywhere on github.  Is there a chance a release could be cut with those fixes included?

This is the post that contained the fixed dll: http://forum.kerbalspaceprogram.com/index.php?/topic/36371-12-procedural-fairings-320-november-8/&do=findComment&comment=2897179

**Comment by e-dog** [comment]
Ask KortexM, it's his changes, not mine.
