### ISSUE TITLE
Update to 1.3?

### ISSUE THREAD

**Issue by flashmeow** [e-dog/ProceduralFairings#29]
Since the 1.3 update, KSP crashes on launch when PF is installed.
Is there a fix or something?

**Comment by rsparkyc** [comment]
@e-dog, perhaps this will be the best place for you to see this, as I can see you haven't been on the forums lately.  I was considering taking over ownership, but wanted to make a good-faith effort to see if you still wanted to maintain this.

**Comment by flashmeow** [comment]
@rsparkyc I think it's time you create a fork and update it.
Maybe post to CKAN as well?

**Comment by e-dog** [comment]
@rsparkyc Go ahead, I don't think I'll have time for it anytime soon. Feel free to ask me anything about the code.

**Comment by rsparkyc** [comment]
I've made a release for 1.3 here: https://github.com/rsparkyc/ProceduralFairings/releases

**Comment by flashmeow** [comment]
THANK YOU SO MUCH!
I really hate dealing with stock fairings. 
😃
